name: Go Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Build frontend
        working-directory: ./frontend
        run: |
            npm install
            npm run build

      - name: Build backend
        run: VERSION="${{ github.ref_name }}" make build

      - name: Create new release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/simplelinkshortener_linux_x64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete old releases
        uses: dev-drprasad/delete-older-releases@v0.2.1
        with:
          keep_latest: 3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
